@startmindmap
title CloudWatch Logs Group Structure for Audit as a Service

* AuditService
** [FORMAT]
*** Environment
**** Data Type
***** Audited Entity
****** Audit Type
******* Audit Event
** [SAMPLE]
*** /production
**** /Providers
***** /Documents
****** /General
******* /Upload
******* /Access
******* /Metadata/Access
******* /Verification/Start
******* /Verification/Complete
******* /Verification/Reject
****** /HIPAA
******* /Upload
******* /Access
******* /Metadata/Access
****** /PII
******* /Upload
******* /Access
******* /Metadata/Access
****** /PCI-DSS
******* /Upload
******* /Access
******* /Metadata/Access
***** /Profile

@endmindmap
