@startmindmap S3 Storage Structure
* S3 Storage Structure
** /billing
*** /uploaded
**** {document-owner-id}
***** /billing-statements
****** /STATEMENT-2024-12-20.PDF
****** /STATEMENT-2024-12-21.PDF
***** /payment-receipts
****** /RECEIPT-2024-12-20-00394.PDF
****** /RECEIPT-2024-12-21-05472.PDF
***** /<other-supported-categories>
****** ...
*** /verified
**** {document-owner-id}
*** /rejected
**** {document-owner-id}
** /insurance
*** ...
** /legal
*** ...
** /hr
*** ...
** /<other_supported_types>
*** ...
@endmindmap
