@startmindmap Get Document Details API Validation
* Get Document Details API Validation
** initiatorsystemcode
*** Type: STRING
*** Enum: SupportedInitiatorSystemCodes
*** Required: Yes
** requestorid
*** Type: STRING
*** Required: Yes
** requestorip
*** Type: STRING
*** Pattern: SupportedParamsPatterns.IP
*** Required: Yes
** documenttype
*** Type: STRING
*** Enum: SupportedDocumentTypes
*** Required: Yes
** documentid
*** Type: STRING
*** Required: Yes
@endmindmap
