@startuml Documents Audit
!define RECTANGLE class

actor User
actor ComplianceOfficer

package "AWS Cloud" {
    [Amazon API Gateway] as APIGateway
    [Document Upload Lambda] as UploadLambda
    [Audit Lambda] as AuditLambda
    [S3 Event Lambda] as S3Lambda
    [Documents S3] as S3
    [Audit DynamoDB] as DynamoDB
    
}
[Upload Dashboard] as UploadDashboard
[Audit Dashboard] as AuditDashboard

' Layout settings
top to bottom direction
left to right direction

' User interactions
User --> UploadDashboard : Request Uploading document
UploadDashboard --> APIGateway : Request Pre-Signed URL
APIGateway --> UploadLambda : Generate Pre-Signed URL
UploadLambda --> APIGateway : Return Pre-Signed URL
APIGateway --> UploadDashboard : Return Pre-Signed URL
UploadDashboard --> S3 : Upload document via Pre-Signed URL
S3 --> S3Lambda : Create event triggers Lambda
S3Lambda --> DynamoDB: Saves audit event

ComplianceOfficer --> AuditDashboard : Opens Dashboard
AuditDashboard --> APIGateway : Request Audit data
APIGateway --> AuditLambda : Request Audit data
AuditLambda --> DynamoDB : Get Audit data
DynamoDB --> AuditLambda : Return Audit data
AuditLambda --> APIGateway : Return Audit data
APIGateway --> AuditDashboard : Return data to Audit Dashboard
@enduml
