@startuml  Get Document Metadata Workflow
actor User
participant "UI" as UI
participant "API Gateway" as APIGW
participant "Step Function" as SF
participant "DynamoDB" as DynamoDB
participant "Audit Service" as Audit

User -> UI : Clicks Document Details Page to view metadata
UI -> APIGW : Request to open document
APIGW -> SF : Trigger Step Function

SF -> DynamoDB : Retrieve Document metadata
DynamoDB -> SF : Return metadata

SF -> Audit : Record audit event

SF -> UI : Return metadata to UI
UI -> User : Display metadata to User

@enduml
